### ISSUE TITLE
Breakpoints in em units

### ISSUE THREAD

**Issue by caycefischer** [csswizardry/csswizardry-grids#1]
Would it be possible (given Sass syntax, and the math involved) to write our breakpoints in `em`s instead of pixels? `em`-based media queries are more flexible and considerate of the content than pixel values.

Articles:
- [@viljamis](http://viljamis.com/blog/2012/scaling-with-em-units/)
- [Cloud 4](http://blog.cloudfour.com/the-ems-have-it-proportional-media-queries-ftw/)
- [filament group](http://filamentgroup.com/lab/how_we_learned_to_leave_body_font_size_alone/)
- [@_joshnh](http://joshnh.com/2011/07/26/are-you-using-ems-with-your-media-queries/)

**Comment by csswizardry** [comment]
Yeah I’ll think it over :)

**Comment by chris-pearce** [comment]
Yeah I think `em`s are the way to go (just divide BP by 16), also I'd use `em` or `rem` (if `rem` need a `px` fall-back for old IE) for the gutter.

**Comment by davidspiess** [comment]
:+1: thumbs up :)

**Comment by csswizardry** [comment]
I believe @BPScott’s work in #6 has solved this :)
