### ISSUE TITLE
Empty HTML comments

### ISSUE THREAD

**Issue by lionel-m** [csswizardry/csswizardry-grids#12]
Hello,

I would like to use your solution in a CMS but it is very difficult because there is the empty comments to insert each time. Content elements are automatically generated most of the time...

Is there another solution ?

Thx

**Comment by csswizardry** [comment]
You can try this: https://github.com/csswizardry/inuit.css/issues/170#issuecomment-14859371 :)

**Comment by csswizardry** [comment]
I have actually fixed this in this project :) https://github.com/csswizardry/csswizardry-grids/commit/86fcbd463461140254efc16cae6068ef488d3e8a

**Comment by lionel-m** [comment]
Thank you ! :+1:

**Comment by hugows** [comment]
This is back in 5.0, right?
