### ISSUE TITLE
equal height columns

### ISSUE THREAD

**Issue by oksana-khristenko** [csswizardry/csswizardry-grids#13]
It would be nice to have support for equal height grid items for cases where there is a need to set a vertical border or background on children of `.grid__item` blocks.

One of the solutions would be to use overflow hidden on `grid--equal-height` and a large padding and negative bottom margin on `.grid__item` children (see http://mattkirman.com/2009/10/12/equal-height-columns-with-pure-css/), but:
- it's a hack which requires more markup if you need a vertical border (nesting another element into `.grid__item` - for example, `.grid__item__inner` to apply negative margin, positive padding and a vertical border to; the reason is because applying those on `.grid__item` does not work with a border);
- it would work for cases when all equal height columns are in one row horizontally; it might not work nicely or as expected though when `$responsive` is set to true and you try to apply responsive classes like `palm-one-third`.

Any thoughts on a better implementation?

**Comment by csswizardry** [comment]
Hey, although – in theory – this is a nice idea, I have a few reservations:
1. As you point out, most methods are super hacky.
2. As you point out, there is a lot of other stuff going on; single rows, juggling it with the responsiveness etc.
3. csswizardry-grids is intended to solve the problem of responsive grids, so I’d always be reluctant to add other functionality that departs from that ‘roadmap’ at all.

Unless something really bulletproof and simple shows up then I can’t see this making it in, I’m afraid. Thanks though!

H
