### ISSUE TITLE
grid-media-query comment

### ISSUE THREAD

**Issue by noslouch** [csswizardry/csswizardry-grids#14]
Hey Harry,

Thanks for being so responsive (heh) to all the issues. I have a question about line 167 in the file "Enclose a block of code with a media query as named in `$breakpoints`." 

Not sure how to take that: are you saying this is a way to implement our own media queries in our styles?

I've been using this mixin from css-tricks, even if it does end up duplicating things in the compiled code: 

```
@mixin breakpoint($point) {
    @if $point == mobile-only {
        @media only screen and (max-width:480px) { @content; }
    }
    @else if $point == tablet-only {
        @media only screen and (min-width:481px) and (max-width:1023px) { @content; }
    }
    @else if $point == mobile-and-tablet {
        @media only screen and (max-width:1023px)  { @content; }
    }
    @else if $point == tablet-and-up {
        @media only screen and (min-width:481px) { @content; }
    }
    @else if $point == desk-only {
        @media only screen and (min-width:1024px) { @content; }
    }
}
```

**Comment by csswizardry** [comment]
@BPScott wrote that for us :) It’s library code so [not _really_ intended to be used by users](https://github.com/csswizardry/csswizardry-grids/blob/master/csswizardry-grids.scss#L164-L165) of csswizardry-grids. It just allows us to spin out our MQs for csswizardr-grids and csswizardry-grids alone :)

You _could_ reuse it, but it’s not intended to be so therefore comes without guarantee :)

**Comment by BPScott** [comment]
Hi @noslouch,

I sat on the fence over this one a little bit :) This does indeed do the same thing as your `breakpoint` mixin (assuming you've defined those point names in `$breakpoints`), though as @csswizardry says, it's not explicitly stated for public usage and thus has the potential to be changed at any time without warning so relying on it might bite you if you later upgrade csswizardry-grids without paying attention.

Personally I think it's useful enough to be recognised for public-use (and would be a drop-in replacement the `media-query` mixin in inuit.css). In my current project I use it within my standard stylesheets. That project a bit of a special case though as I've gone retro and kept support for IE7 on my grid object so it is incompatible with future versions of csswizardry-grids anyway.

**Comment by noslouch** [comment]
Hi @BPscott,

I hear ya about being upgrade-friendly. The nice thing about that mixin is
the ability to nest within it, which can reduce mq-bloat in the compiled
css. Just needs a little mindfulness as you go along.

How are you supporting ie7? MQ polyfill?

**Comment by BPScott** [comment]
Nope, going old-school and replacing the .grid class with one that uses floats and utilizing a .grid__inner element, as per [Inuit 4.1.5](https://github.com/csswizardry/inuit.css/blob/d54ae59742e7cf05d33dfe845586f58ebc9dc046/inuit.css/partials/objects/_grids-ie7.scss)
