### ISSUE TITLE
Silent classes

### ISSUE THREAD

**Issue by maxkarkowski** [csswizardry/csswizardry-grids#16]
I tried to work with the silent classes but i can't get it right. 
I set $mobile-first to false and silent-classes true:
My css is:

```
.container {
    @extend %grid;
    background-color: #aaa;
}
.half {
    @extend %grid-item;
    @extend %one-half;
}
```

HTML like this:

```
<div class="container">
    <div class="half">
        <div class="demo">Test</div>
    </div>
    <div class="half">
        <div class="demo">Test</div>
    </div>
</div>
```

The Two divs with the class "half" are below each other and not in one row.

**Comment by csswizardry** [comment]
You need to remove the whitespace between grid items: https://github.com/csswizardry/csswizardry-grids#usage
