### ISSUE TITLE
mixed concepts of grid alignment and order of grid items

### ISSUE THREAD

**Issue by oksana-khristenko** [csswizardry/csswizardry-grids#17]
When the order of grid items is reversed, the desired behaviour is not
necessarily to align the entire grid to the right. It can be seen when
grid items widths don't add up to 1 (for example, they add up to three
quarters) like so:

```
<div class="grid--rev">
  <div class="grid__item  one-quarter">
        <p class="demo-block">Grid 1.1</p>
    </div>
  <div class="grid__item one-quarter">
        <p class="demo-block">Grid 1.2</p>
    </div>
</div>
```

Was it for a particular reason that `text-align:right` was added to `grid--rev` (cross browser bug etc.)?

If not, better to separate concepts of order and alignment:
- remove `text-align:right` from `grid--rev` and added
  `text-align:left`;
- add `grid--right` modifier to manage right alignment of grid;

Fixed here: https://github.com/oksana-khristenko/csswizardry-grids/tree/feature/order-alignment

**Comment by csswizardry** [comment]
This never even crossed my mind, thanks so much! :D I’ll get it worked in when I get chance :)

**Comment by oksana-khristenko** [comment]
Sent pull request :) My first one, so let me know if it works or you prefer to just copy the code.

**Comment by csswizardry** [comment]
[Thanks!](https://github.com/csswizardry/csswizardry-grids/commit/a03c0773573368bc189c20e8a3dbe5266d0abe44)
