### ISSUE TITLE
Filling a full row overflows to the next row.

### ISSUE THREAD

**Issue by mikegehard** [csswizardry/csswizardry-grids#20]
Thanks for your work on this.

I am trying to get a simple grid working with one grid div and three grid__item divs set at class = one-third.

When I do this, the last div moves down to the next row.

I have also tried with one-half and two divs and I get the same issue.

Am I missing something small?

**Comment by csswizardry** [comment]
Read on from here: https://github.com/csswizardry/csswizardry-grids#classes-in-markup

You need to remove the whitespace.

**Comment by mikegehard** [comment]
Thank you.
