### ISSUE TITLE
Just curious - why quarters?

### ISSUE THREAD

**Issue by johjacb** [csswizardry/csswizardry-grids#27]
IMO - seems that "fourths" would be a more natural fit, given its usage in a system of fractions:

thirds
fourths
fifths 
sixths

Quarters seems out of place to me, but its likely an American/British difference?

Anyways, just curious about it. Keep up the stellar work.

**Comment by Igelkottegrodan** [comment]
Good comment and I totally agree. I've actually added this to my own projects because I feel fourths is more natural than quarters even if they are the same thing! It might be because of what @johjacb said.

**Comment by andykirk** [comment]
Well, we don't use 'fourths' in the UK, so for me it feels totally _un_natural :-)

**Comment by s4wny** [comment]
Why not use both? Push your changes as a pull request.

**Comment by csswizardry** [comment]
Fourths sounds _weird_! Do people say fourths?! I’ve never heard anyone say fourths. It’s always been quarters for as long as I have ever known.

**Comment by crispen-smith** [comment]
Canadians say Quarters in just about every context I can think of.  Even in music where we disagree with the British Nomenclature (we use the quarter notes instead of semiquaver).

**Comment by johjacb** [comment]
But fourths has the word four in it! :)

Definitely an American/British and apparently Canadian difference.

Here's some more info: http://english.stackexchange.com/questions/103188/three-quarters-vs-three-fourths

**Comment by andykirk** [comment]
"But fourths has the word four" - what kind of argument is that!? :-)
'halves' doesn't have the word 'two' in it. :-D

**Comment by johjacb** [comment]
a weak one. very weak.

**Comment by crispen-smith** [comment]
I also did a casual survey of my US friends via Facebook and the few responses I got did confirm that at least in Detroit it's Quarters.  So, I don't think that it's a universal American practice either.

As for the stack exchange question;  in most of the instances cited to support the idea of using three fourths occasionally, most of those examples would have been better served with 75% and the few that wouldn't would have been better served with three quarters.

**Comment by Igelkottegrodan** [comment]
@andykirk, same argument as @csswizardry gave which was "Fourths sounds weird!". :) It would be nice if someone did as @s4wny proposed, a pull request. Then you can use either quarters or fourths, whatever you think is more intuitive. Because if we drop "what sounds weird or not" the fact remains that the "syntax" is a bit off and less streamline if fourths does not exist.

**Comment by csswizardry** [comment]
Reading back my comment, I did sound very dismissive. I did not intend to be, so for that I apologise.

I still can’t get my head round the fourths thing, though. It isn’t consistent if you ask me; consistent would be, as @andykirk pointed out, using ‘oneths’ and ‘twoths’.

Out of interest, and this isn’t meant to sound condescending, but how would people who say ‘fourths’ say the time 12:15?

**Comment by crispen-smith** [comment]
I'm open to doing a pull request for this, just to increase the flexibility.

My only concern is that we end up polluting the namespace and while this is CSS rather than hard-core programing I still believe that good practices should be adhered to.  If increasing the flexibility shouldn't happen I won't do a pull but if it makes everyone's life easier it seems a trivial (ish) edit.

**Comment by johjacb** [comment]
I use quarters and fourths regularly. It just seems more natural - to me personally - to use fourths here. Of course, I can just add it to my own project to avoid pollution.

But, like I said, I was just curious.

I would say "twelve fifteen".

**Comment by Igelkottegrodan** [comment]
Well speaking time, you always use quarters so it's really a very bad example. Same goes for currency. In mathematical terms however, I would never use quarters. 2/4 is not two quarters, it's two fourths. But that might just be me. :)

**Comment by andykirk** [comment]
Actually, 2/4 is a half ;-).

In maths we still say 'quarters'. We never say 'fourths' for anything, as far as I’m aware. It’s not a term that exists in our vernacular.

**Comment by Igelkottegrodan** [comment]
Haha touché, fair enough. :D
