### ISSUE TITLE
concerning overflow

### ISSUE THREAD

**Issue by johjacb** [csswizardry/csswizardry-grids#28]
Sorry if this has been covered, I searched the issues and documentation and couldn't find anything...

I've noticed content in the **last** column that overflows (such as a long word) causes a horizontal scrollbar. 

Do you recommend adding an overflow declaration or would you advise using a different strategy?

Thank you!

**Comment by csswizardry** [comment]
Please can you provide a demo of this?

**Comment by johjacb** [comment]
Here you go: http://jsfiddle.net/gPq5p/

**Comment by csswizardry** [comment]
In which browser? This isn’t breaking for me in Chrome…

**Comment by johjacb** [comment]
Latest versions of Chrome, Safari, FF

![screen shot 2013-05-15 at 10 00 04 am](https://f.cloud.github.com/assets/2394337/507457/6ade5e3c-bd70-11e2-8b99-aaf2a7bd7e01.png)
![screen shot 2013-05-15 at 10 01 22 am](https://f.cloud.github.com/assets/2394337/507458/6ae304c8-bd70-11e2-91b4-274d0f2f3e01.png)

**Comment by csswizardry** [comment]
Oh, apologies, I totally misunderstood. If you have content that is too wide for your viewport then that isn’t a grid system issue, it’s a content issue, I’m afraid.

Perhaps use some CSS truncation on your content, or word breaking etc :)

**Comment by johjacb** [comment]
Right - my main question (if you look at the original) is how you would best handle this.

Would you favor truncation instead of overflow:hidden?

Sorry for the confusion!

**Comment by csswizardry** [comment]
It totally depends on the content and context. I quite like CSS truncation for non-essential text, but it does fall outside the scope of the grid system :)

**Comment by johjacb** [comment]
Yep - totally understand. Thanks for your input.

If I may - let me give you the scenario I have. I have a 4 column grid, each has an h2 for a title. Near the palm/lap breakpoint, where the columns are narrow, the title flows over, because the h2's are big (inuit's default 30px size).

What would you do?

**Comment by csswizardry** [comment]
If the words themselves are quite long I would just word break/CSS hyphenate them :)

**Comment by johjacb** [comment]
cheers - thanks
