### ISSUE TITLE
where are the placeholder definitions?

### ISSUE THREAD

**Issue by glomotion** [csswizardry/csswizardry-grids#29]
hey there,

having issues trying to implement the 'silent-classes' version of ur grid. 

when i goto compile: i get this error:

> > > Change detected at 17:10:51 to: style.scss
> > > WARNING on line 232 of /Users/tim/Desktop/GIT Repos/msnd-programme-cutup/scss/style.scss: ".scene .grid-content" failed to @extend "%grid".
> > > The selector "%grid" was not found. This will be an error in future releases of Sass. Use "@extend %grid !optional" if the extend should be able to fail. WARNING on line 235 of /Users/tim/Desktop/GIT Repos/msnd-programme-cutup/scss/style.scss: ".scene .left" failed to @extend "%grid__item". The selector "%grid__item" was not found. This will be an error in future releases of Sass. Use "@extend %grid__item !optional" if the extend should be able to fail. WARNING on line 236 of /Users/tim/Desktop/GIT Repos/msnd-programme-cutup/scss/style.scss: ".scene .left" failed to @extend "%desk--one-third".
> > > The selector "%desk--one-third" was not found. This will be an error in future releases of Sass. Use "@extend %desk--one-third !optional" if the extend should be able to fail. identical style.css

upon investigation i noticed - that no where in ur csswizardry-grids.scss file - do you define the SASS placeholders that you say you need to apply to DOM elements ie "@extend %grid". Am i missing something here?

**Comment by glomotion** [comment]
ok, figured out the issue. 

tis just the doco in the README.md is wrong. 

syntax should be: @extend .grid; not @extend %grid;

:)

**Comment by csswizardry** [comment]
What version of Sass are you running? I just used the README demo code and it compiled perfectly…

**EDIT:** I also just did this from a fresh clone… worked fine.

**Comment by glomotion** [comment]
hrmmm.... strange. I'm using Scout to compile. Maybe it's not quite up to date..

**Comment by glomotion** [comment]
closed.
