### ISSUE TITLE
Setting grid__item width to 100%

### ISSUE THREAD

**Issue by robinbentley** [csswizardry/csswizardry-grids#3]
Would there be any milage in setting the grid__item width to 100% by default.

My thinking is that nine times in ten, at mobile sizes you're going to want a single column so it would remove the need declare one-whole repeatedly. 

This way you just add classes for your breakpoints as you size upwards and if you wanted to have more than one column at mobile you can simply add an un-prefixed or 'palm-' class to those elements before your 'lap-' or 'desk-' classes.

It just cleans the mark-up slightly for those who would rather use classes than extends. I've probably defeated a point somewhere though so just slap me.

Any Thoughts? Cheers!

**Comment by chris-pearce** [comment]
I agree esp. when working mobile first, at 'palm' size like you say you pretty much need everything linear so that should be the default rather than treating the edge cases as the default making you declare `.one-whole` classes over & over.

**Comment by waynemoir** [comment]
By doing so you would lose the ability for a .grid_item to reduce in width below 100% to fit the size of the content; whether this matters or not I couldn't say.

**Comment by csswizardry** [comment]
@waynemoir Grids should only be less than 100% if they’re explicitly told to be; they should never ‘hug’ their content :)

**Comment by waynemoir** [comment]
Then this change would be the way to go?

**Comment by csswizardry** [comment]
In real terms it doesn’t really change anything, it just gives you a preset default rather than you having to pick one :)

**Comment by csswizardry** [comment]
Done in 1.2, thanks :)
