### ISSUE TITLE
hide classes

### ISSUE THREAD

**Issue by fxck** [csswizardry/csswizardry-grids#32]
I remember in one of the previous version of inuit to be able to use `lap-hide`, `palm-hide` etc, is there a similar helper in cwg?

**Comment by dotnetCarpenter** [comment]
I haven't seen it in csswizardry-grids but you can easily implement it in your own project by using the `grid-media-query` mixin from csswizardry-grids.
The following snippet does what you want:

``` sass
@each $breakpoint in $breakpoints{
    $name: nth($breakpoint, 1);
    @include grid-media-query( $name ) {
        .#{$name}-hide { display: none; }
    }
}
```

**Comment by csswizardry** [comment]
Hi!

Yeah, this is not really in the scope of a grid system, but you can use the snippet above in your own Sass files later on, by all means :)

**Comment by judehansen** [comment]
are there any plans to integrate this?
