### ISSUE TITLE
Why no floats?

### ISSUE THREAD

**Issue by chris-pearce** [csswizardry/csswizardry-grids#4]
I'm just wondering mainly out of curiosity why you've gone with `display: inline-block` over `float` like you've used for your **Inuit** grid which is almost identical (maybe you're planning on changing Inuit to be the same)? And I'm also curious about the fix for removing the dreaded white space created between inline block elements, how did you come up with that? Good work!

**Comment by csswizardry** [comment]
> I'm just wondering mainly out of curiosity why you've gone with `display: inline-block` over `float`…

Floats are pretty heavy-handed and can be a bit unpredictable. The `display:inline-block;` method just seems to play a little nicer.

> maybe you're planning on changing Inuit to be the same

I’m hoping to maybe port this grid system back into inuit.css.

> And I'm also curious about the fix for removing the dreaded white space created between inline block elements, how did you come up with that? 

That is something I’ve seen dotted about, I don’t know its origin but I know @necolas uses it for something as well…

**Comment by chris-pearce** [comment]
Thanks for the feedback, yeah floats can be a pain.

**Comment by willit0** [comment]
For some reason inline-block css property isn't working for me. Here you can see what's happening.

http://jsfiddle.net/kJp8H/

If you float .grid__item elements to the left it will work. Otherwise it won't.

Any idea why?

**Comment by csswizardry** [comment]
Because – as per the docs – you need to remove the whitespace between `.grid__items`: https://github.com/csswizardry/csswizardry-grids#usage

**Comment by hamishtaplin** [comment]
Using floats for grids is pretty commonplace and, whilst not without its problems, at least negates the need for whitespace-removal hacks that makes the grid quite cumbersome to use with a CMS. Would it be feasible to bake both systems in and allow users to configure with a "$use-floats:false!default" flag?

EDIT: I just retro-fitted this myself and it's working perfectly so far. Happy to submit a pull-request if it's something you'd consider.
