### ISSUE TITLE
.grid--center seems to be missing

### ISSUE THREAD

**Issue by benlwilliams** [csswizardry/csswizardry-grids#43]
https://github.com/csswizardry/csswizardry-grids#centred-grids-grid--center

This is not working and I can't find it in any of the .scss files of the inuit.css folder.  I'm I missing something?

**Comment by csswizardry** [comment]
This is a csswizardry-grids feature, and isn’t (yet) in inuit.css: https://github.com/csswizardry/csswizardry-grids/blob/master/csswizardry-grids.scss#L296-L306

Cheers,
H
