### ISSUE TITLE
Grid won't align correctly without adding HTML comments in the markup

### ISSUE THREAD

**Issue by unintelligible** [csswizardry/csswizardry-grids#45]
When using 1/4 widths, each element in the grid wraps unless I add HTML comments between each of the grid elements. Any idea why?

Without HTML comments (doesn't work): http://jsfiddle.net/CN8ba/

With HTML comments (works): http://jsfiddle.net/8X5dZ/

Ideally, I'd like to avoid littering my HTML with comments to make the grid system work, if I can avoid it :-)

**Comment by HellPat** [comment]
Search for other issues. There are so many of them.

You can minify your html. This will work, too.
Or do like so:

``` html
  <div class="grid__item">
      foo
  </div
><div class="grid__item">
     bar
  </div>
```

**Comment by bryanaka** [comment]
this issue has been known for a while. its a problem with inline-block elements. They inherently have whitespace in between them, which throws off the grid.

#33 is a good solution for development, but after that I suggest looking for an html minifier or something akin to jinja/twig's whitespace control helper. handlebars is getting a similar helper in 1.1. I am still looking for a solution for erb...

**Comment by unintelligible** [comment]
Thanks guys. Closing this as it obviously isn't an issue per se.
