### ISSUE TITLE
Howto align grid vertically?

### ISSUE THREAD

**Issue by dotnetCarpenter** [csswizardry/csswizardry-grids#65]
I'm having an issue with aligning two section with different widths. Before I spend too much time trying to get it to work, I want to check with you guys if it's even possible or a known limitation to csswizardry-grids.

My use-case is illustrated here: http://jsfiddle.net/dotnetCarpenter/CMn9u/

The top section is one-whole with a one-quarter and a three-quarters element inside. The next section, which I want to align with the one-quarter, is a two-quarters element with 2 two-quarters elements inside. It's paramount to the design that I'm able to do this. How, is not that important, but the visual alignment must look precise.

I greatly appreciate any pointers, suggestions or what ever you can come up with!

Cheers

**Comment by csswizardry** [comment]
[Like this…?](http://jsfiddle.net/csswizardry/CMn9u/3/)

The key is that `.grid` classes should never be applied to the same element as a `.grid__item` class :)

I also tidied everything up a little to make it more readable :)

**Comment by dotnetCarpenter** [comment]
Wow thanks Harry! You saved my week! Your example also makes it clear to me when white-space is actually an issue and when not. It has been more than a year since I used csswizardry-grids. It is nice to be back in good company. :)
