### ISSUE TITLE
Your grid is broken when using columns 11/12, 1/12

### ISSUE THREAD

**Issue by abacaj** [csswizardry/csswizardry-grids#84]
The following code does not work and the columns do not fit, they collapse under each other.

```
   <div class="grid">
            <div class="grid__item  lap--one-half  eleven-twelfths">
                <p>11/12</p>
            </div>
            <div class="grid__item  lap--one-half  one-twelfth">
                <p>1/12</p>
            </div>
        </div>
```

Please see this codepen: http://codepen.io/anon/pen/BNyQZP

**Comment by patrick-wc** [comment]
Your code is different in your codepen, you need the desk-- prefix and for
there to be no whitespace between the two .grid__item div's:

``````
   ```<div class="grid">
        <div class="grid__item  lap--one-half  desk--eleven-twelfths">
            <p>11/12</p>
        </div><!--
   --><div class="grid__item  lap--one-half  desk--one-twelfth">
            <p>1/12</p>
        </div>
    </div>```
``````

http://codepen.io/patrickwc/pen/aOzByZ

**Comment by abacaj** [comment]
Is this because of inline-block instead of float left as some other grids use?

**Comment by patrick-wc** [comment]
Yes, read Classes in markup here: https://github.com/csswizardry/csswizardry-grids

**Comment by abacaj** [comment]
You also added comment block... This is a lot of unnecessary overhead to create a grid!

**Comment by patrick-wc** [comment]
Not really, you can always minify HTML anyway. With inline-block you can do reversed and vertically aligned grids which aren't possible with float based grid systems.

**Comment by abacaj** [comment]
Ok how about this solution:

http://codepen.io/anon/pen/doPOgZ

No longer is it necessary for comment blocks.

**Comment by abacaj** [comment]
Ok how about this solution:

http://codepen.io/anon/pen/KpwNGP

No longer is it necessary for comment blocks.
